groups: []

resource_types: []

resources:
- name: source
  type: git
  source:
    branch: master
    private_key: ((git-key))
    uri: git@github.com:ikhripunov-org/fe.sturdy-pancake.git
- name: version
  type: semver
  source:
    driver: s3
    initial_version: 0.0.1
    access_key_id:     ((aws.access_key_id))
    secret_access_key: ((aws.secret_access_key))
    bucket: concourse-resources
    region_name: us-west-2
    key: fe.sturdy-pancake/version
- name: sturdy-pancake
  type: s3
  source:
    bucket: concourse-resources
    regexp: dist/sturdy-pancake-(.*).war
    access_key_id: ((aws.access_key_id))
    secret_access_key: ((aws.secret_access_key))
    region_name: us-west-2

jobs:
- name: build
  serial: true
  plan:
  - aggregate:
    - get: source
      trigger: true
    - get: version
      params:
        pre: patch
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: node
          tag: alpine
      params:
        AWS_ACCESS_KEY_ID: ((aws.access_key_id))
        AWS_SECRET_ACCESS_KEY: ((aws.secret_access_key))
      run:
        path: sh
        args:
          - -c
          - |
            ./node_modules/.bin/vue-cli-service build
            ls ./dist
  - aggregate:
    - put: version
      params:
        file: version/number
    - put: sturdy-pancake
      params:
        file: sturdy-pancake-*.zip
- name: deploy
  serial: true
  plan:
    - aggregate:
      - get: version
        passed: [build]
        trigger: true
      - get: sturdy-pancake
        passed: [build]
    - task: deploy
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: mesosphere/aws-cli
            tag: latest
        params:
          AWS_ACCESS_KEY_ID: ((aws.access_key_id))
          AWS_SECRET_ACCESS_KEY: ((aws.secret_access_key))
          AWS_DEFAULT_REGION: us-west-2
        run:
          path: sh
          args:
            - -c
            - |
              ls .
    - put: version
      params:
        file: version/number
